social_django/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

social_django/groups/urls.py
from django.urls import path, include
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.GroupList.as_view(), name='list'),
    path('create/', views.GroupCreate.as_view(), name='create'),
    path('posts/in/<slug>', views.GroupDetail.as_view(),name='detail'),
    path('join/<slug>',views.GroupJoin.as_view(),name = 'join'),
    path('leave/<slug>',views.GroupLeave.as_view(),name = 'leave'),

]

social_django/posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='list'),
    path('create/', views.PostCreate.as_view(), name='create'),
    path('by/<username>/<pk>/', views.PostDetail.as_view(),name='detail'),
    path('by/<username>/', views.UserPosts.as_view(),name='for_user'),
    path('delete/<pk>',views.PostDelete.as_view(),name = 'delete'),
    path('update/<pk>',views.PostUpdate.as_view(),name = 'update'),

]

social_django/social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bye/',views.ByePage.as_view(), name='bye'),
    path('groups/',include('groups.urls')),
    path('posts/',include('posts.urls')),
]

social_django/accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):
    
    def __str__(self):
        return "@{}".format(self.username)
    
    

social_django/groups/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.urls import reverse
User = get_user_model()
# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField()
    members = models.ManyToManyField(User, through="GroupMember")
    
    def __str__(self):
        return self.name
        
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)
        
    def get_absolute_url(self):
        return reverse('groups:detail', kwargs={'slug':self.slug})
    
    class Meta:
        ordering=['name']
    
class GroupMember(models.Model):
    group = models.ForeignKey(Group,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username
        
    class Meta:
        unique_together = ('group','user')

social_django/posts/models.py
from django.db import models
from groups.models import Group
from django.contrib.auth import get_user_model
from django.urls import reverse
User = get_user_model()
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'username': self.user.username,'pk': self.pk})
        
    class Meta:
        ordering = ['-created_at']

social_django/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class UserCreateForm(UserCreationForm):
    class Meta:
        # fields = '__all__'
        fields = ('username','email','password1','password2')
        model = get_user_model()

social_django/accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from . import forms
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('accounts:login')
    

social_django/groups/views.py
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView, DetailView, RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db import IntegrityError
from .models import Group, GroupMember

# Create your views here.
class GroupList(ListView):
    model = Group
    
class GroupCreate(LoginRequiredMixin,CreateView):
    model = Group
    fields = ('name','description')
    
class GroupDetail(DetailView):
    model = Group
    
class GroupJoin(LoginRequiredMixin,RedirectView):
    #코드 실행 후 리다이렉트 할 주소 설정
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:detail', kwargs={'slug':self.kwargs.get('slug')})
    #코드 실행
    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))
        
        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,"실패")
        else:
            messages.success(self.request,"성공")
            
        return super().get(request,*args,**kwargs)
        
class GroupLeave(LoginRequiredMixin,RedirectView):
    
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:detail', kwargs={'slug':self.kwargs.get('slug')})
        
    def get(self,request,*args,**kwargs):
        
        try:
            membership = GroupMember.objects.filter(user= self.request.user,group__slug=self.kwargs.get('slug')).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request,"없음")
        else:
            membership.delete()
            messages.success(self.request,"지움")
            
        return super().get(request,*args,**kwargs)

social_django/posts/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView,DeleteView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post
from groups.models import GroupMember
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
# Create your views here.

User = get_user_model()

class PostList(ListView):
    model = Post
    
class PostCreate(LoginRequiredMixin,CreateView):
    model = Post
    fields = ('title','message','group')
    
    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)
        
class PostDetail(DetailView):
    model = Post
    
class UserPosts(ListView):
    model = Post
    template_name = 'posts/user_post_list.html'
    
    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('post_set').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.post_set.all()
            
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context
        
class PostDelete(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('posts:list')
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)
        
    
class PostUpdate(LoginRequiredMixin,UpdateView):
    model = Post
    fields = ('message',)
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

social_django/social/views.py
from django.views.generic import TemplateView
from django.shortcuts import render

# Create your views here.

class HomePage(TemplateView):
    template_name = 'index.html'
    
class ByePage(TemplateView):
    template_name = 'bye.html'

social_django/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body_block %}
<div class="container">
    <form method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Submit"/>
    </form>
</div>
{% endblock %}

social_django/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body_block %}
<div class="container">
    <form method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Submit"/>
    </form>
</div>
{% endblock %}

social_django/groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    <div class="row">
        {% block pregroup %} {% endblock %}
        {% block group_content %} {% endblock %}
        {% block postgroup %} {% endblock %}
    </div>
</div>
{% endblock %}

social_django/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}
{% block pregroup %}
<p><h1>{{group.name}}</h1></p>
<p><h2>member count : {{group.members.count}}</h2></p>
<p>{{group.description}}</p>
{% if user in group.members.all %}
<a href="{% url 'groups:leave' slug=group.slug %}" type="button" class="btn btn-warning">
    <i class="fas fa-sign-out-alt"></i> leave
</a>

{% else %}

<a href="{% url 'groups:join' slug=group.slug %}" type="button" class="btn btn-warning"><i class="fas fa-sign-out-alt"></i> 그룹 참여</a>
{% endif %}
{% endblock %}

social_django/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap4 %}
{% block group_content %}
<form method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Submit"/>
</form>
{% endblock %}

social_django/groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}
        {% block pregroup %}
        <!--유저정보 출력-->
        <div class="col-md-4">
            {% if user.is_authenticated %}
            <h2>반갑습니다 <a href="">@{{user.username}}</a></h2>
            {% endif %}
            <p>여기는 그룹페이지입니다</p>
        
        {% if user.is_authenticated %}
        <a href="{% url 'groups:create' %}" class="btn btn-warning"><i class="fas fa-plus"></i>create new group</a>
        {% endif %}
        </div>
        {% endblock %}
        {% block group_content %}
        <!--그룹 리스트 출력-->
        <div class="col-md-8">
            {% for group in group_list %}
            <div class="jumbotron">
                <h3>{{group.name}}</h3>
                <button type="button" class="btn btn-primary"> Member <span class="badge badge-light">{{group.members.count}}</span>
</button>
<a href="{%url 'groups:detail' slug=group.slug %}" class="btn btn-primary">그룹보기</a>
{% if user.is_authenticated %}
<a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-warning"><i class="fas fa-plus"></i>그룹참여</a>
{% endif %}
            </div>
            {% endfor %}
        </div>
        
        {% endblock %}
        {% block postgroup %} 
        {% endblock %}

social_django/posts/templates/posts/_post.html
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src=".../100px180/" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
    <p class="card-text">{{post.created_at}}</p>
     <a href="{% url 'posts:for_user' post.user.username %}">
    <p class="card-text">{{post.user.username}}</p></a>
    <a href="{% url 'posts:detail' username=post.user.username pk=post.pk %}" class="btn btn-primary">글보기</a>
  </div>
</div>

social_django/posts/templates/posts/post_base.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    <div class="row">
        {% block prepost %} {% endblock %}
        {% block post_content %} {% endblock %}
        {% block post_post %} {% endblock %}
    </div>
</div>
{% endblock %}

social_django/posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}
{% load bootstrap4 %}
{% block post_content %} 
<form method='post'>
    {% csrf_token %}
    <input type="submit" value="Submit"/>
</form>

{% endblock %}

social_django/posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
<div class="jumbotron">
  <h1 class="display-4">{{post.title}}</h1>
  <p class="lead">{{post.message}}</p>
  <hr class="my-4">
  <p>{{post.created_at}}</p>
  {% if user.is_authenticated and post.user == user %}
  <a class="btn btn-primary btn-lg" href="{% url 'posts:update' post.pk%}" role="button">수정</a>
  <a class="btn btn-danger btn-lg" href="{% url 'posts:delete' post.pk%}" role="button">삭제</a>
  {% endif %}
</div>
{% endblock %}

social_django/posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap4 %}
{% block post_content %} 
<form method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Submit"/>
</form>

{% endblock %}

social_django/posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}
{% block prepost %}
<div class="col-md-4">
    {% if user.is_authenticated %}
    <h2>반갑습니다 <a href="{% url 'posts:for_user' user.username %}">@{{user.username}}</a></h2>
    {% endif %}
    <p>여기는 포스트페이지입니다</p>
        
        {% if user.is_authenticated %}
        <a href="{% url 'posts:create' %}" class="btn btn-warning"><i class="fas fa-plus"></i>create new post</a>
        {% endif %}
        </div>
{% endblock %}
{% block post_content %} 
<div class="col-md-8">
    {% for post in post_list %}
    {% include 'posts/_post.html' %}
    {% endfor %}
</div>
{% endblock %}

social_django/posts/templates/posts/post_update.html
{% extends 'posts/post_base.html' %}
{% load bootstrap4 %}
{% block post_content %} 
<form method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Submit"/>
</form>

{% endblock %}

social_django/posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
{% for post in post_list %}
{% include 'posts/_post.html' %}
{% endfor %}
{% endblock %}

social_django/templates/base.html
<!DOCTYPE html>
{% load staticfiles  %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'posts:list'%}">Post <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'groups:list'%}">Group</a>
      </li>
      {% if user.is_authenticated %}
            <li class="nav-item">
        <a class="nav-link disabled" href="{% url 'accounts:logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
    {% block body_block %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

social_django/templates/bye.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body_block %}
{%% load staticfiles }
<div class="container">
잘가
<img src='{% static "img/a.jpg"%}'></img>
</div>
{% endblock %}

social_django/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<h1>인덱스다 맨이야</h1>
{% endblock %}