django_003/account/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name='account'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    # path('logout/', views.logout, name='logout'),


]

django_003/either/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/', include('question.urls')),
    path('accounts/', include('account.urls')),
]

django_003/question/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'question'
urlpatterns = [
    path('', views.list, name='list'),
    path('create/', views.create, name='create'),
    path('<int:id>/detail/', views.detail, name='detail'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/comment/create/', views.comment_create,name='comment_create'),
    path('<int:id>/comment/<int:comment_id>/delete/', views.comment_delete,name='comment_delete')
]

django_003/account/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=50)
    birth_date = models.DateField()
    

django_003/question/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Question(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    answerA = models.CharField(max_length=500)
    answerB = models.CharField(max_length=500)
    
    def __str__(self):
        return self.title
        
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_list = [['A','left'],['B','right']]
    answer = models.CharField(max_length=100, choices=answer_list)
    content = models.CharField(max_length=500)
    
    

django_003/account/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        # fields = '__all__'
        fields = ['nickname','birth_date']
    

django_003/question/forms.py
from django import forms
from .models import Question, Comment

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        # fields = '__all__'
        fields = ['title','answerA','answerB']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = '__all__'
        fields = ['answer','content']

django_003/account/views.py
from django.shortcuts import render, redirect, resolve_url
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from account.forms import ProfileForm
# Create your views here.

def login(request):
    if request.user.is_authenticated:
        return redirect('question:list')
    else:
        if request.method == "POST": # 사용자가 로그인을 요청했으면?
            form = AuthenticationForm(request, request.POST)
            if form.is_valid():
                auth_login(request, form.get_user())
                return redirect('question:list')
        else: # 로그인을 위한 폼을 요청했으면?
            form = AuthenticationForm()
            
            return render(request,"account/login.html",{'form':form})

def logout(request):
    auth_logout(request)
    return redirect('question:list')
    
def signup(request):
    if request.user.is_authenticated:
        return redirect('question:list')
    else:
        if request.method == "POST": # 사용자가 로그인을 요청했으면?
            form = UserCreationForm(request.POST)
            pro_form = ProfileForm(request.POST)
            if form.is_valid() and pro_form.is_valid():
                user = form.save()
                profile = pro_form.save(commit=False)
                profile.user = user
                profile.save()
                auth_login(request, user)
                return redirect('question:list')
        else: # 로그인을 위한 폼을 요청했으면?
            form = UserCreationForm()
            pro_form = ProfileForm()
        return render(request,"account/signup.html",{'form':form,"pro_form":pro_form})

django_003/question/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render, resolve_url, redirect
from question.forms import QuestionForm, CommentForm
from .models import Question,Comment
from django.contrib.auth.decorators import login_required
# Create your views here.

def list(request):
    questions = Question.objects.all()
    paginator = Paginator(questions, 5) # Show 25 contacts per page
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    # return render(request, 'list.html', {'contacts': contacts})
    return render(request,'question/list.html',{'questions':contacts})

@login_required    
def create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.user = request.user
            question.save()
            return redirect(resolve_url("question:list"))
    else:
        form = QuestionForm()
        return render(request,'question/create.html',{'form':form})
        
def detail(request,id):
    question = Question.objects.get(id=id)
    form = CommentForm(initial={'question':id})
    A = question.comment_set.all().filter(answer="A")
    B = question.comment_set.all().filter(answer="B")
    if len(A)+len(B) == 0:
        A_per = 0
        B_per = 0
    else:
        A_per = len(A)/(len(A) + len(B)) * 100
        B_per = len(B)/(len(A) + len(B)) * 100
    return render(request,'question/detail.html',{'question':question,'form':form,'A':A,'B':B,'A_per':A_per,'B_per':B_per})

def update(request,id):
    question = Question.objects.get(id=id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            return redirect(resolve_url('question:detail',id))
    else:
        form = QuestionForm(instance=question)
        return render(request,'question/update.html',{'form':form,'question':question})

def delete(request,id):
    question = Question.objects.get(id=id)
    question.delete()
    return redirect(resolve_url('question:list'))
    
def comment_create(request,id):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.question = Question.objects.get(id=id)
            comment.save()
            return redirect(resolve_url('question:detail',id))
    else:
        form = CommentForm()
        return redirect(resolve_url('question:detail',id))
    # return render(request,'question/detail.html',{'question':question,'form':form})
    
def comment_delete(request,id,comment_id):
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return redirect(resolve_url('question:detail',id))

django_003/question/templates/question/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'question:list' %}">Either</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'question:create' %}">새글쓰기</a>
      </li>
          {% if user.is_authenticated %}
    <!-- 로그아웃 버튼-->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:logout' %}">로그아웃</a>
      </li>
    {% else %}
    <!--로그인 버튼-->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:login' %}">로그인</a>
      </li>

    {% endif %}
    </ul>
  </div>
</nav>
    <div class='container'>
    {% block body_block %}
    {% endblock %}
    </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

django_003/question/templates/question/create.html
{% extends 'question/base.html'%}
{% block body_block %}
<form action="{% url 'question:create' %}" method="post">
    {% csrf_token %}
    <table>{{form}}</table>
    <input type="submit"/>
</form>

{% endblock %}

django_003/question/templates/question/detail.html
{% extends 'question/base.html'%}
{% block body_block %}

<h1>{{question.title}}</h1><br>
<h3>작성자: {{question.user}}</h3>
<h2>{{question.answerA}} : {{A|length}} VS {{question.answerB}} : {{B|length}}</h2>
<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: {{A_per}}%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100">{{A_per|floatformat}}</div>
  <div class="progress-bar bg-info" role="progressbar" style="width: {{B_per}}%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">{{B_per|floatformat}}</div>
</div>
    <form action="{% url 'question:comment_create' question.id %}" method="post">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="Submit"/>
    </form>
<br>
<a href="{% url 'question:update' id=question.id %}" class="btn btn-primary" role="button">수정</a> <a href="{% url 'question:delete' id=question.id %}" class="btn btn-primary" role="button">삭제</a>
<br><br>
<h3>댓글 <a href="{% url 'question:comment_create' question.id %}" class="btn btn-primary" role="button">댓글작성</a> </h3>
<p>선택 | 이유</p>
{% for comment in question.comment_set.all %}
<p>{{comment.answer}} | {{comment.content}} - <a href="{% url 'question:comment_delete' id=question.id comment_id=comment.id %}" class="btn btn-primary" role="button">삭제</a></p>
{% endfor %}

{% endblock %}

django_003/question/templates/question/list.html
{% extends 'question/base.html'%}
{% block body_block %}

{% load bootstrap_pagination %}

{% for question in questions %}
<p>{{question.title}} | <a href="{% url 'question:detail' id=question.id %}" class="btn btn-primary" role="button">글보기</a> <a href="{% url 'question:update' id=question.id %}" class="btn btn-primary" role="button">수정</a> <a href="{% url 'question:delete' id=question.id %}" class="btn btn-primary" role="button">삭제</a></p>
{% endfor %}
{% bootstrap_paginate questions range=5 show_first_last=True %}
{% endblock %}

django_003/question/templates/question/update.html
{% extends 'question/base.html'%}
{% block body_block %}
<form action="{% url 'question:update' question.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit"/>
</form>
{% endblock %}