django_002/board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('post.urls'))
]

django_002/post/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.list, name='list'),
    path('create/',views.create,name='create'),
    path('<int:id>/detail/',views.detail, name='detail'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete', views.delete, name='delete'),
    path('model_create', views.model_create, name='model_create'),
    path('<int:id>/model_update', views.model_update, name='model_update')
    
]

django_002/post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title

django_002/post/forms.py
from django import forms
from .models import Post
class PostForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'editable'}))
    
        
class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

django_002/post/views.py
from django.shortcuts import render, redirect, resolve_url
from .forms import PostForm, PostModelForm
from .models import Post
# Create your views here.
def list(request):
    posts = Post.objects.all()
    return render(request,"post/list.html",{'posts':posts})
    
def create(request):
    if request.method == "POST":
        # 저장로직
        form = PostForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            # title = form.cleand_data.get('title')
            content = form.cleaned_data['content']
            Post.objects.create(title=title,content=content)
            
            return redirect(resolve_url('post:list'))
        pass
    else:
        # 입력할 수 있는 폼 리턴
        form = PostForm()
        return render(request,"post/create.html", {'form':form})
        
def detail(request,id):
    post = Post.objects.get(id=id)
    return render(request,'post/detail.html',{'post':post})
    
def update(request,id):
    post = Post.objects.get(id=id)
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            title = request.POST.get('title')
            content = form.cleaned_data.get('content') 
            # post.update(title=title,content=content)
            post.title = title
            post.content = content
            post.save()
            return redirect(resolve_url('post:detail',id))
    else:
        form = PostForm({'title':post.title,'content':post.content})
        return render(request,'post/update.html',{'form':form,'post':post})
    
def delete(request,id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect(resolve_url('post:list'))
    

def model_create(request):
    if request.method == "POST":
        # 저장하는 로직
        pass
    else:
        # 폼을 보여주는 로직
        form = PostModelForm()
        return render(request,'post/model_create.html',{'form':form})
    
def model_update(request,id):
    pass

django_002/post/templates/post/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'post:create' %}">게시물 작성하기</a>
    {% block body_block %}
    {% endblock %}
</body>
</html>

django_002/post/templates/post/create.html
{% extends 'post/base.html'%}
{% block body_block %}
<!-- 폼을 넣어야 함 -->
<form action="{% url 'post:create' %}" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit"/>
</form>
<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

django_002/post/templates/post/detail.html
{% extends 'post/base.html'%}
{% block body_block %}
<h1>단일 페이지이다</h1>
<a href="{% url 'post:update' id=post.id %}">수정</a> | <a href="{% url 'post:delete' id=post.id %}">삭제</a>
<p>{{post.title}} : </p>
{{post.content|safe}}

{% endblock %}

django_002/post/templates/post/list.html
{% extends 'post/base.html'%}
{% block body_block %}
<h1>리스트입니다</h1>
{% for post in posts %}
<p>{{post.title}} | {{post.content}}</p>
<a href="{% url 'post:detail' id=post.id %}">detail 링크</a>
{% endfor %}
{% endblock %}

django_002/post/templates/post/model_create.html
{%extends 'post/base.html'%}

{%block body_block%}
    {{form}}
{%endblock%}

django_002/post/templates/post/update.html
{% extends 'post/base.html'%}
{% block body_block %}
<!-- 폼을 넣어야 함 -->
<form action="{% url 'post:update' id=post.id %}" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit"/>
</form>
<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}