CBV_CRUD/CBV_CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/', include('questions.urls'))
]

CBV_CRUD/questions/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'questions'
urlpatterns = [
    path('', views.index.as_view(), name='index'),
    path('create/', views.create.as_view(), name='create'),
    path('<int:pk>/', views.read.as_view(), name='read'),
    path('update/<int:pk>', views.update.as_view(), name='update'),
    path('delete/<int:pk>', views.delete.as_view(), name='delete'),

]

CBV_CRUD/questions/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=100)
    answerA = models.CharField(max_length=100)
    answerB = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('questions:index')

CBV_CRUD/questions/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Question
# Create your views here.
class index(ListView):
    template_name='questions/index.html'
    model = Question
    
class create(CreateView):
    model = Question
    fields = ('title','answerA','answerB')

    
class read(DetailView):
    template_name='questions/read.html'
    model = Question
    
class update(UpdateView):
    model = Question
    fields = ('title','answerA','answerB')
    
class delete(DeleteView):
    model = Question
    success_url = reverse_lazy('questions:index')

CBV_CRUD/questions/templates/questions/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body_block %}
    {% endblock %}
</body>
</html>

CBV_CRUD/questions/templates/questions/index.html
{% extends 'questions/base.html' %}
{% block body_block %}
{% for question in question_list %}
<p>{{question.title}} | {{question.answerA}} | {{question.answerB}} | <a href="{% url 'questions:update' pk=question.pk %}">수정</a> | <a href="{% url 'questions:delete' pk=question.pk %}">삭제</a></p>
{% endfor %}
{% endblock %}

CBV_CRUD/questions/templates/questions/question_confirm_delete.html
{% extends 'questions/base.html' %}
{% block body_block %}
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Submit"/>
</form>
{% endblock %}

CBV_CRUD/questions/templates/questions/question_form.html
{% extends 'questions/base.html' %}
{% block body_block %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit"/>
</form>
{% endblock %}

CBV_CRUD/questions/templates/questions/read.html
{% extends 'questions/base.html' %}
{% block body_block %}
{{question.title}} | {{question.answerA}} | {{question.answerB}} | 
{% endblock %}